export const mockRecipes = [
  {
    id: 11,
    name: 'Chicken Biryani',
    difficulty: 'Medium',
    caloriesPerServing: 550,
    image: 'https://cdn.dummyjson.com/recipe-images/11.webp',
    rating: 5,
  },
  {
    id: 12,
    name: 'Chicken Karahi',
    difficulty: 'Easy',
    caloriesPerServing: 420,
    image: 'https://cdn.dummyjson.com/recipe-images/12.webp',
    rating: 4.8,
  },
  {
    id: 13,
    name: 'Aloo Keema',
    difficulty: 'Medium',
    caloriesPerServing: 380,
    image: 'https://cdn.dummyjson.com/recipe-images/13.webp',
    rating: 4.6,
  },
  {
    id: 14,
    name: 'Chapli Kebabs',
    difficulty: 'Medium',
    caloriesPerServing: 320,
    image: 'https://cdn.dummyjson.com/recipe-images/14.webp',
    rating: 4.7,
  },
  {
    id: 15,
    name: 'Saag (Spinach) with Makki di Roti',
    difficulty: 'Medium',
    caloriesPerServing: 280,
    image: 'https://cdn.dummyjson.com/recipe-images/15.webp',
    rating: 4.3,
  },
  {
    id: 16,
    name: 'Japanese Ramen Soup',
    difficulty: 'Medium',
    caloriesPerServing: 480,
    image: 'https://cdn.dummyjson.com/recipe-images/16.webp',
    rating: 4.9,
  },
  {
    id: 17,
    name: 'Moroccan Chickpea Tagine',
    difficulty: 'Easy',
    caloriesPerServing: 320,
    image: 'https://cdn.dummyjson.com/recipe-images/17.webp',
    rating: 4.5,
  },
  {
    id: 18,
    name: 'Korean Bibimbap',
    difficulty: 'Medium',
    caloriesPerServing: 550,
    image: 'https://cdn.dummyjson.com/recipe-images/18.webp',
    rating: 4.9,
  },
  {
    id: 19,
    name: 'Greek Moussaka',
    difficulty: 'Medium',
    caloriesPerServing: 420,
    image: 'https://cdn.dummyjson.com/recipe-images/19.webp',
    rating: 4.3,
  },
  {
    id: 20,
    name: 'Butter Chicken (Murgh Makhani)',
    difficulty: 'Medium',
    caloriesPerServing: 480,
    image: 'https://cdn.dummyjson.com/recipe-images/20.webp',
    rating: 4.5,
  },
];
