import Head from 'next/head';
import { useContext, useEffect } from 'react';
import { useRouter } from 'next/router';
import { GetServerSideProps } from 'next';

import SearchBar from '../components/SearchBar/SearchBar';
import ResultsList from '../components/ResultList/ResultList';
import ErrorBoundary from '../components/ErrorBoundary/ErrorBoundary';
import Flyout from '../components/Flyout/Flyout';
import { ThemeContext } from '../providers/ThemeProvider';
import { useActions } from '../hooks/useActions';
import { useAppSelector } from '../hooks/useAppSelector';
import styles from '../styles/Home.module.css';
import RecipeDetails from '../components/RecipeDetails/RecipeDetails';

interface HomeProps {
  initialData: [];
  query: string;
  page: number;
}

const Home: React.FC<HomeProps> = ({ initialData, query, page }) => {
  const router = useRouter();

  const { openDetails, closeDetails } = useActions();
  const { isOpen } = useAppSelector((state) => state.openDetails);

  const themeContext = useContext(ThemeContext);
  if (!themeContext) {
    throw new Error('useContext must be used within a ThemeProvider');
  }
  const theme = themeContext.isLightTheme;

  useEffect(() => {
    if (router.query.details) {
      console.log(router.query.details);
      openDetails();
    } else {
      closeDetails();
    }
  }, [router.query.details]);

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={theme ? styles.lightTheme : styles.darkTheme}>
        <div className={styles.container}>
          <h1>Recipes</h1>
          <ErrorBoundary>
            <SearchBar />
            <div className={`${styles.mainContent} ${isOpen ? styles.shifted : ''}`}>
              <ResultsList initialData={initialData} query={query} page={page} />
              {isOpen && <RecipeDetails id={router.query.details as string} />}
            </div>
            <Flyout />
          </ErrorBoundary>
        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { page = 1, query = '' } = context.query;
  //   details = ''
  const response = await fetch(
    `https://dummyjson.com/recipes/search?q=${query}&limit=${10}&skip=${(Number(page) - 1) * 10}`,
  );
  const data = await response.json();

  return {
    props: {
      page: Number(page),
      initialData: data,
      query: query as string,
    },
  };
};

export default Home;
